Repository THM-Health/PILOS, pull requests merged in 2020-09, with the labels that each got.

#48 Fix wrong end meeting callback salt
  app/Http/Controllers/api/v1/MeetingController.php
  app/Http/Controllers/api/v1/RoomController.php
  app/Meeting.php
  database/factories/RoomType.php
  tests/Feature/api/v1/Room/FileTest.php
  tests/Feature/api/v1/Room/RoomTest.php
Labels: bug

#49 Add pagination to room list
  CHANGELOG.md
  app/Http/Controllers/api/v1/RoomController.php
  app/Http/Controllers/api/v1/RoomTypeController.php
  config/settings.php
  resources/js/components/Room/NewRoomComponent.vue
  resources/js/components/Room/RoomComponent.vue
  resources/js/lang/de/app.js
  resources/js/lang/en/app.js
  resources/js/views/rooms/Index.vue
  resources/sass/app.scss
  routes/api.php
  tests/Feature/api/v1/Room/RoomTest.php
  tests/Feature/api/v1/Room/RoomTypeTest.php
  tests/Frontend/components/Room/NewRoom.spec.js
  tests/Frontend/components/Room/RoomList.spec.js
Labels: enhancement

#56 Clear current user in frontend on 401 error
  resources/js/app.js
Labels: bug, enhancement
