Repository THM-Health/PILOS, pull requests merged in 2021-05, with the labels that each got.

#137 Bugfix error on empty access code
  CHANGELOG.md
  resources/js/lang/de/rooms.js
  resources/js/lang/en/rooms.js
  resources/js/views/rooms/View.vue
  tests/Frontend/views/rooms/View.spec.js
Labels: bug

#116 Refactor room permissions
  .babelrc
  CHANGELOG.md
  app/Enums/RoomUserRole.php
  app/Http/Controllers/api/v1/RoomFileController.php
  app/Http/Controllers/api/v1/RoomMemberController.php
  app/Http/Controllers/api/v1/UserController.php
  app/Http/Middleware/RoomAuthenticate.php
  app/Http/Requests/AddRoomMember.php
  app/Http/Requests/UpdateRoomMember.php
  app/Http/Resources/Room.php
  app/Http/Resources/UserSearch.php
  app/Meeting.php
  app/Policies/RoomPolicy.php
  app/Room.php
  database/seeds/RolesAndPermissionsSeeder.php
  resources/js/components/Room/AdminComponent.vue
  resources/js/components/Room/FileComponent.vue
  resources/js/components/Room/MembersComponent.vue
  resources/js/components/Room/RoomComponent.vue
  resources/js/components/Room/SettingsComponent.vue
  resources/js/lang/de/app.js
  resources/js/lang/de/rooms.js
  resources/js/lang/en/app.js
  resources/js/lang/en/rooms.js
  resources/js/policies/RoomPolicy.js
  resources/js/views/rooms/Index.vue
  resources/js/views/rooms/View.vue
  routes/web.php
  tests/Feature/api/v1/Room/FileTest.php
  tests/Feature/api/v1/Room/MembershipTest.php
  tests/Feature/api/v1/Room/RoomTest.php
  tests/Feature/api/v1/UserTest.php
  tests/Frontend/components/Room/DeleteRoom.spec.js
  tests/Frontend/components/Room/NewRoom.spec.js
  tests/Frontend/components/Room/RoomFile.spec.js
  tests/Frontend/components/Room/RoomMembers.spec.js
  tests/Frontend/components/Room/RoomSettings.spec.js
  tests/Frontend/policies/RoomPolicy.spec.js
  tests/Frontend/views/ForgotPassword.spec.js
  tests/Frontend/views/rooms/Index.spec.js
  tests/Frontend/views/rooms/OwnIndex.spec.js
  tests/Frontend/views/rooms/View.spec.js
Labels: enhancement

#140 138 Hide room types from search
  CHANGELOG.md
  app/Http/Controllers/api/v1/RoomTypeController.php
  resources/js/views/rooms/Index.vue
  tests/Feature/api/v1/Room/RoomTypeTest.php
  tests/Frontend/views/rooms/Index.spec.js
Labels: enhancement

#127 Restrict room type access
  CHANGELOG.md
  app/Enums/CustomStatusCodes.php
  app/Http/Controllers/api/v1/RoomController.php
  app/Http/Controllers/api/v1/RoomTypeController.php
  app/Http/Requests/CreateRoom.php
  app/Http/Requests/RoomTypeRequest.php
  app/Http/Requests/UpdateRoomSettings.php
  app/Http/Resources/Room.php
  app/Http/Resources/RoomType.php
  app/Role.php
  app/Room.php
  app/RoomType.php
  app/Rules/ValidRoomType.php
  database/migrations/2021_03_12_144148_create_role_room_type_table.php
  database/seeds/RolesAndPermissionsSeeder.php
  resources/js/components/Room/SettingsComponent.vue
  resources/js/components/RoomType/RoomTypeSelect.vue
  resources/js/lang/de/rooms.js
  resources/js/lang/de/settings.js
  resources/js/lang/en/rooms.js
  resources/js/lang/en/settings.js
  resources/js/views/rooms/View.vue
  resources/js/views/settings/roomTypes/View.vue
  resources/lang/de/app.php
  resources/lang/de/validation.php
  resources/lang/en/app.php
  resources/lang/en/validation.php
  tests/Feature/api/v1/Room/RoomTest.php
  tests/Feature/api/v1/Room/RoomTypeTest.php
  tests/Frontend/components/Room/NewRoom.spec.js
  tests/Frontend/components/Room/RoomSettings.spec.js
  tests/Frontend/components/RoomType/RoomTypeSelect.spec.js
  tests/Frontend/views/rooms/View.spec.js
  tests/Frontend/views/settings/roomTypes/View.spec.js
  tests/Unit/Rules/ValidRoomTypeTest.php
Labels: enhancement

#118 Greenlight import tool
  CHANGELOG.md
  app/Console/Commands/ImportGreenlight.php
  app/Console/Kernel.php
  app/Listeners/SetUserModelDefaults.php
  app/Listeners/SetUserModelLdapAuthenticatorType.php
  app/Providers/EventServiceProvider.php
  composer.json
  composer.lock
  tests/TestCase.php
  tests/Unit/Console/BuildHistoryTest.php
  tests/Unit/Console/CreateAdminUserTest.php
  tests/Unit/Console/DeleteUnverifiedNewUsersTest.php
  tests/Unit/Console/ImportGreenlightTest.php
  tests/Unit/Console/helper/GreenlightRoom.php
  tests/Unit/Console/helper/GreenlightSharedAccess.php
  tests/Unit/Console/helper/GreenlightUser.php
Labels: documentation, enhancement
