Repository THM-Health/PILOS, pull requests merged in 2024-09, with the labels that each got.

#1383 Improve file upload user experience
  lang/en/rooms.php
  resources/js/components/RoomTabFilesUploadButton.vue
Labels: UI

#1384 Fix not room tab selected on permission or room role change
  resources/js/components/RoomTabSection.vue
Labels: bug, UI

#1421 Improve error handling in room
  resources/js/components/RoomCard.vue
  resources/js/components/RoomDeleteButton.vue
  resources/js/components/RoomFavoriteButton.vue
  resources/js/components/RoomHeader.vue
  resources/js/components/RoomJoinButton.vue
  resources/js/components/RoomMembershipButton.vue
  resources/js/components/RoomTabDescription.vue
  resources/js/components/RoomTabFiles.vue
  resources/js/components/RoomTabFilesDeleteButton.vue
  resources/js/components/RoomTabFilesEditButton.vue
  resources/js/components/RoomTabFilesUploadButton.vue
  resources/js/components/RoomTabFilesViewButton.vue
  resources/js/components/RoomTabHistory.vue
  resources/js/components/RoomTabHistoryAttendanceButton.vue
  resources/js/components/RoomTabHistoryStatisticButton.vue
  resources/js/components/RoomTabMembers.vue
  resources/js/components/RoomTabMembersAddSingleModal.vue
  resources/js/components/RoomTabMembersBulkDeleteButton.vue
  resources/js/components/RoomTabMembersBulkEditButton.vue
  resources/js/components/RoomTabMembersBulkImportModal.vue
  resources/js/components/RoomTabMembersDeleteButton.vue
  resources/js/components/RoomTabMembersEditButton.vue
  resources/js/components/RoomTabPersonalizedLinks.vue
  resources/js/components/RoomTabPersonalizedLinksAddButton.vue
  resources/js/components/RoomTabPersonalizedLinksDeleteButton.vue
  resources/js/components/RoomTabPersonalizedLinksEditButton.vue
  resources/js/components/RoomTabRecordings.vue
  resources/js/components/RoomTabRecordingsDeleteButton.vue
  resources/js/components/RoomTabRecordingsEditButton.vue
  resources/js/components/RoomTabRecordingsViewButton.vue
  resources/js/components/RoomTabSection.vue
  resources/js/components/RoomTabSettings.vue
  resources/js/components/RoomTransferOwnershipButton.vue
  resources/js/composables/useApi.js
  resources/js/composables/useRoomHelpers.js
  resources/js/constants/events.js
  resources/js/services/Api.js
  resources/js/views/RoomsView.vue
Labels: bug, frontend, refactor
