Repository THM-Health/PILOS, pull requests merged in 2024-08, with the labels that each got.

#1309 Hide bulk edit/delte room member checkboxes if user does not have permission to manage room
  resources/js/components/RoomTabMembers.vue
Labels: bug, frontend

#1308 Fix room file error handling
  resources/js/components/RoomTabFiles.vue
  resources/js/components/RoomTabFilesDeleteButton.vue
  resources/js/components/RoomTabFilesEditButton.vue
Labels: bug, frontend

#1293 Fix wrong number of rooms shown on initial load of rooms index page
  resources/js/views/RoomsIndex.vue
Labels: bug, frontend, UI

#1299 Fix no error message shown on users errors (bulk edit)
  resources/js/components/RoomTabMembersBulkDeleteButton.vue
  resources/js/components/RoomTabMembersBulkEditButton.vue
Labels: bug, frontend

#1341 Fix room settings style
  resources/js/components/RoomTabSettings.vue
  resources/js/components/RoomTypeChangeButton.vue
Labels: bug, UI
