Repository THM-Health/PILOS, pull requests merged in 2025-01, with the labels that each got.

#1727 Fix xdebug always enabled
  CHANGELOG.md
  docker/app/Dockerfile
Labels: bug

#1758 Fix wrong error message shown for 422 errors when verifying email
  CHANGELOG.md
  resources/js/views/VerifyEmail.vue
Labels: bug, frontend

#1600 Improve error handling in room stats and attendance
  .github/workflows/ci.yml
  CHANGELOG.md
  app/Enums/CustomStatusCodes.php
  app/Http/Controllers/api/v1/MeetingController.php
  compose.test.local.yml
  docker-compose-dev.yml
  docs/docs/development/07-testing.md
  eslint.config.js
  lang/en/app.php
  package-lock.json
  package.json
  resources/js/components/RoomTabHistory.vue
  resources/js/components/RoomTabHistoryAttendanceButton.vue
  resources/js/components/RoomTabHistoryStatisticButton.vue
  resources/js/env.js
  tests/Backend/Feature/api/v1/Room/RoomStatisticTest.php
  tests/Frontend/e2e/RoomsViewHistoryMeetingActions.cy.js
  tests/Frontend/fixtures/files/statsGraph.png
  tests/Visual/.happo.js
  tests/Visual/cypress.config.js
  tests/Visual/e2e/RoomsViewHistoryMeetingActions.cy.js
  tests/Visual/fixtures/config.json
  tests/Visual/fixtures/currentUser.json
  tests/Visual/fixtures/room.json
  tests/Visual/fixtures/roomHistory.json
  tests/Visual/fixtures/roomHistoryStats.json
  tests/Visual/support/commands.js
  tests/Visual/support/commands/interceptCommands.js
  tests/Visual/support/e2e.js
Labels: UI

#1772 Fix inconsistent select loading states
  CHANGELOG.md
  resources/js/components/SettingsRoomTypesDeleteButton.vue
  resources/js/components/TimezoneSelect.vue
  resources/js/views/AdminRoomTypesView.vue
  resources/js/views/AdminServerPoolsView.vue
  resources/js/views/AdminUsersIndex.vue
  resources/js/views/RoomsIndex.vue
  tests/Frontend/e2e/RoomsIndex.cy.js
  tests/Frontend/e2e/UserProfileBase.cy.js
  tests/Frontend/e2e/UserProfileSecurity.cy.js
Labels: frontend

#1785 Enforce locale in cypress
  .github/workflows/ci.yml
  cypress.config.js
  package.json
Labels: tests

#1794 Fix input fields not disabled correctly on login page and improve tests
  CHANGELOG.md
  resources/js/components/LoginTabLdap.vue
  resources/js/components/LoginTabLocal.vue
  tests/Frontend/e2e/Login.cy.js
Labels: bug, tests, frontend

#1802 Fix missing form validation in forgot password
  CHANGELOG.md
  resources/js/views/ForgotPassword.vue
Labels: UI

#1801 Fix missing form validation feedback on password fields
  CHANGELOG.md
  resources/js/components/LoginTabLdap.vue
  resources/js/components/LoginTabLocal.vue
  tests/Frontend/e2e/Login.cy.js
Labels: UI
